[package]
name = "number_guesser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "23.1.0"
soroban-token-sdk = "23.1.0"   # if youâ€™re using token features
